-- ADMINISTRACIÓN DE ROLES

-- 1
select * from dba_tab_privs
where privilege = 'RESOURCE';

-- 2
CREATE ROLE DEV;
GRANT CREATE TABLE,CREATE VIEW TO DEV;
GRANT SELECT ON C##EMI.CUSTOMERS TO DEV;

-- 3
-- 3.1
GRANT RESOURCE TO Bob,;
GRANT DEV TO Bob,;

-- 3.2
GRANT SELECT_CATALOG_ROLE TO BOB;

-- 4


-- 5
 CREATE VIEW CUST_VIEW
AS SELECT * FROM EMI.CUSTOMERS;
-- 6
CREATE VIEW CUST_VIEW
AS SELECT * FROM EMI.CUSTOMERS;